<#
.SYNOPSIS
  Build entry point. Bumps the build number in version.json (semantic version),
  regenerates version.props (imported by Directory.Build.props so every assembly
  is stamped), then builds the solution. Optionally runs tests.

.EXAMPLE
  ./build.ps1                       # bump build number, Release build
  ./build.ps1 -Configuration Debug  # Debug build (still bumps)
  ./build.ps1 -Test                 # build then run tests
  ./build.ps1 -NoBump               # build without incrementing the build number
#>
[CmdletBinding()]
param(
    [string]$Configuration = 'Release',
    [switch]$Test,
    [switch]$NoBump
)

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$versionFile = Join-Path $root 'version.json'

$version = Get-Content $versionFile -Raw | ConvertFrom-Json

if (-not $NoBump) {
    $version.build = [int]$version.build + 1
    # Write back with a stable shape (major, minor, build).
    $ordered = [ordered]@{ major = [int]$version.major; minor = [int]$version.minor; build = [int]$version.build }
    ($ordered | ConvertTo-Json) | Set-Content $versionFile -Encoding utf8
}

$semVer = "{0}.{1}.{2}" -f [int]$version.major, [int]$version.minor, [int]$version.build
$asmVer = "$semVer.0"
Write-Host "Version: $semVer (configuration: $Configuration)" -ForegroundColor Cyan

# Regenerate the MSBuild props all projects import.
$propsPath = Join-Path $root 'version.props'
@"
<Project>
  <!-- GENERATED by build.ps1 from version.json. Do not edit. -->
  <PropertyGroup>
    <Version>$semVer</Version>
    <AssemblyVersion>$asmVer</AssemblyVersion>
    <FileVersion>$asmVer</FileVersion>
    <InformationalVersion>$semVer</InformationalVersion>
  </PropertyGroup>
</Project>
"@ | Set-Content $propsPath -Encoding utf8

dotnet build (Join-Path $root 'LlmAuth.slnx') -c $Configuration /p:Version=$semVer /p:AssemblyVersion=$asmVer /p:FileVersion=$asmVer
if ($LASTEXITCODE -ne 0) { throw "Build failed." }

if ($Test) {
    dotnet test (Join-Path $root 'LlmAuth.slnx') -c $Configuration --no-build
    if ($LASTEXITCODE -ne 0) { throw "Tests failed." }
}

Write-Host "Build succeeded: $semVer" -ForegroundColor Green
