<#
.SYNOPSIS
  Build entry point. Defaults to the Rust/ratatui implementation.
  Pass -Legacy to build the C# / .NET solution instead.

  Bumps the build number in version.json (semantic version) and — for legacy
  builds — regenerates version.props (imported by Directory.Build.props so every
  assembly is stamped). Optionally runs tests.

.EXAMPLE
  ./build.ps1                       # bump build number, Rust Release build (default)
  ./build.ps1 -NoBump               # Rust build without incrementing the build number
  ./build.ps1 -Test                 # Rust build then run Rust tests
  ./build.ps1 -Configuration Debug  # Rust Debug build (still bumps)
  ./build.ps1 -Deploy               # Rust build, then install shim via dotnet tool update
  ./build.ps1 -Legacy               # C# / .NET solution build (legacy)
  ./build.ps1 -Legacy -NoBump       # C# build without incrementing
  ./build.ps1 -Legacy -Test         # C# build then run .NET tests
#>
[CmdletBinding()]
param(
    [string]$Configuration = 'Release',
    [switch]$Test,
    [switch]$NoBump,
    [switch]$Deploy,
    # Build the legacy C# / .NET solution instead of the default Rust implementation.
    [switch]$Legacy
)

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot

if ($Legacy) {
    if ($Deploy) {
        throw "-Deploy is supported only for Rust Coda. Use publish.ps1 -Legacy for the C# package."
    }
    # -------------------------------------------------------------------------
    # Legacy path: C# / .NET solution build. Retained for reference; the Rust
    # binary is the primary distribution.
    # -------------------------------------------------------------------------
    $versionFile = Join-Path $root 'version.json'
    $version = Get-Content $versionFile -Raw | ConvertFrom-Json

    if (-not $NoBump) {
        $version.build = [int]$version.build + 1
        $ordered = [ordered]@{ major = [int]$version.major; minor = [int]$version.minor; build = [int]$version.build }
        ($ordered | ConvertTo-Json) | Set-Content $versionFile -Encoding utf8
    }

    $semVer = "{0}.{1}.{2}" -f [int]$version.major, [int]$version.minor, [int]$version.build
    $asmVer = "$semVer.0"
    Write-Host "Version: $semVer (Legacy C# build, configuration: $Configuration)" -ForegroundColor Cyan

    $propsPath = Join-Path $root 'version.props'
    @"
<Project>
  <!-- GENERATED by build.ps1 from version.json. Do not edit. -->
  <PropertyGroup>
    <Version>$semVer</Version>
    <AssemblyVersion>$asmVer</AssemblyVersion>
    <FileVersion>$asmVer</FileVersion>
    <InformationalVersion>$semVer</InformationalVersion>
  </PropertyGroup>
</Project>
"@ | Set-Content $propsPath -Encoding utf8

    dotnet build (Join-Path $root 'LlmAuth.slnx') -c $Configuration /p:Version=$semVer /p:AssemblyVersion=$asmVer /p:FileVersion=$asmVer
    if ($LASTEXITCODE -ne 0) { throw "Build failed." }

    if ($Test) {
        dotnet test (Join-Path $root 'LlmAuth.slnx') -c $Configuration --no-build
        if ($LASTEXITCODE -ne 0) { throw "Tests failed." }
    }

    Write-Host "Build succeeded (legacy C#): $semVer" -ForegroundColor Green
}
else {
    # -------------------------------------------------------------------------
    # Default path: Rust / ratatui build. Delegates to rust/build.ps1.
    # -------------------------------------------------------------------------
    $rustBuild = Join-Path $root 'rust\build.ps1'
    $passthru = @{}
    if ($NoBump)  { $passthru['NoBump'] = $true }
    if ($Test)    { $passthru['Test'] = $true }
    if ($Deploy)  { $passthru['Deploy'] = $true }
    if ($Configuration -ne 'Release') { $passthru['Configuration'] = $Configuration }

    & $rustBuild @passthru
    if ($LASTEXITCODE -ne 0) { throw "Rust build failed." }
}
