<#
.SYNOPSIS
  Build entry point. Defaults to the Rust implementation, which is the engine
  and the shipped `coda` binary.

  Pass -Dotnet to build the remaining .NET surface instead: Coda.Client (the
  out-of-process SDK for the serve protocol) and Coda.Launcher (which packs the
  Rust binary as the Coda.Cli global tool). Bumps the build number in
  version.json and regenerates version.props, which Directory.Build.props
  imports so every assembly is stamped.

.EXAMPLE
  ./build.ps1                       # bump build number, Rust Release build (default)
  ./build.ps1 -NoBump               # Rust build without incrementing the build number
  ./build.ps1 -Test                 # Rust build then run Rust tests
  ./build.ps1 -Configuration Debug  # Rust Debug build (still bumps)
  ./build.ps1 -Deploy               # Rust build, then install shim via dotnet tool update
  ./build.ps1 -Dotnet               # build the .NET solution (Coda.Client, Coda.Launcher)
  ./build.ps1 -Dotnet -Test         # build the .NET solution then run its tests
#>
[CmdletBinding()]
param(
    [string]$Configuration = 'Release',
    [switch]$Test,
    [switch]$NoBump,
    [switch]$Deploy,
    # Build the .NET solution (client SDK + tool launcher) instead of Rust.
    [switch]$Dotnet
)

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot

if ($Dotnet) {
    if ($Deploy) {
        throw "-Deploy builds and installs the Rust binary. Use ./publish.ps1 to pack the Coda.Cli tool."
    }
    # -------------------------------------------------------------------------
    # .NET path: the client SDK and the tool launcher. The agent itself is Rust;
    # nothing here implements one.
    # -------------------------------------------------------------------------
    $versionFile = Join-Path $root 'version.json'
    $version = Get-Content $versionFile -Raw | ConvertFrom-Json

    if (-not $NoBump) {
        $version.build = [int]$version.build + 1
        $ordered = [ordered]@{ major = [int]$version.major; minor = [int]$version.minor; build = [int]$version.build }
        ($ordered | ConvertTo-Json) | Set-Content $versionFile -Encoding utf8
    }

    $semVer = "{0}.{1}.{2}" -f [int]$version.major, [int]$version.minor, [int]$version.build
    $asmVer = "$semVer.0"
    Write-Host "Version: $semVer (.NET build, configuration: $Configuration)" -ForegroundColor Cyan

    $propsPath = Join-Path $root 'version.props'
    @"
<Project>
  <!-- GENERATED by build.ps1 from version.json. Do not edit. -->
  <PropertyGroup>
    <Version>$semVer</Version>
    <AssemblyVersion>$asmVer</AssemblyVersion>
    <FileVersion>$asmVer</FileVersion>
    <InformationalVersion>$semVer</InformationalVersion>
  </PropertyGroup>
</Project>
"@ | Set-Content $propsPath -Encoding utf8

    dotnet build (Join-Path $root 'Coda.slnx') -c $Configuration /p:Version=$semVer /p:AssemblyVersion=$asmVer /p:FileVersion=$asmVer
    if ($LASTEXITCODE -ne 0) { throw "Build failed." }

    if ($Test) {
        dotnet test (Join-Path $root 'Coda.slnx') -c $Configuration --no-build
        if ($LASTEXITCODE -ne 0) { throw "Tests failed." }
    }

    Write-Host "Build succeeded (.NET): $semVer" -ForegroundColor Green
}
else {
    # -------------------------------------------------------------------------
    # Default path: Rust build. Delegates to rust/build.ps1.
    # -------------------------------------------------------------------------
    $rustBuild = Join-Path $root 'rust\build.ps1'
    $passthru = @{}
    if ($NoBump)  { $passthru['NoBump'] = $true }
    if ($Test)    { $passthru['Test'] = $true }
    if ($Deploy)  { $passthru['Deploy'] = $true }
    if ($Configuration -ne 'Release') { $passthru['Configuration'] = $Configuration }

    & $rustBuild @passthru
    if ($LASTEXITCODE -ne 0) { throw "Rust build failed." }
}
