<#
.SYNOPSIS
  Publishes Coda at the CURRENT version (version.json — no bump).

  DEFAULT (Rust/ratatui — primary distribution):
    self-contained   Native Rust binary, no runtime needed.
                     -> publish/self-contained/coda.exe
    framework-dependent  Alias for self-contained; the Rust binary has no
                     framework dependency.
                     -> publish/framework-dependent/coda.exe
    tool             .NET global tool package (Coda.Cli, command `coda`).
                     The package wraps a thin .NET launcher that runs the
                     bundled native binary — the TUI engine is pure Rust.
                     -> publish/tool/*.nupkg
    engine           Standalone, TUI-free `coda-engine` binary (opt-in; not
                     part of `all`). Same core JSON-RPC-over-stdio engine
                     `coda serve` runs, for an external orchestrator/worker/
                     bridge that wants to launch a core-only artifact instead
                     of the unified `coda` binary.
                     -> publish/engine/coda-engine.exe

.EXAMPLE
  ./publish.ps1                         # all three flavors, win-x64
  ./publish.ps1 -Flavor self-contained  # just the standalone exe
  ./publish.ps1 -Flavor tool            # just the global-tool nupkg
  ./publish.ps1 -Flavor engine          # just the standalone coda-engine

.NOTES
  Build the Rust binary before publishing:
    ./rust/build.ps1 -NoBump   # or: cd rust; cargo build --package coda --package coda-engine --release

  Install or upgrade the global tool from the produced package:
    dotnet tool install --global --add-source ./publish/tool Coda.Cli
    dotnet tool update  --global --add-source ./publish/tool Coda.Cli
#>
[CmdletBinding()]
param(
    [ValidateSet('all', 'self-contained', 'framework-dependent', 'tool', 'engine')]
    [string]$Flavor = 'all',
    [ValidateSet('Release', 'Debug')]
    [string]$Configuration = 'Release',
    [string]$Runtime = 'win-x64'
)


$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$publishRoot = Join-Path $root 'publish'

# --- Resolve the current version (no bump) ------------------------------------
$version = Get-Content (Join-Path $root 'version.json') -Raw | ConvertFrom-Json
$semVer = "{0}.{1}.{2}" -f [int]$version.major, [int]$version.minor, [int]$version.build
$asmVer = "$semVer.0"

function Reset-OutputDir {
    param([string]$OutputDir)
    if (Test-Path $OutputDir) { Remove-Item -Recurse -Force $OutputDir }
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
}

# =============================================================================
# Default path: Rust / ratatui primary distribution
# =============================================================================
Write-Host "Publishing Coda $semVer — Rust/ratatui ($Runtime)" -ForegroundColor Cyan

if ($Runtime -ne 'win-x64') {
    throw "The Rust distribution currently packages win-x64 only; requested '$Runtime'."
}
$nativeDir = Join-Path $root "rust\target\$($Configuration.ToLowerInvariant())"
$rustExe = Join-Path $nativeDir 'coda.exe'
if ($Flavor -ne 'engine' -and -not (Test-Path $rustExe)) {
    throw "Rust binary not found at $rustExe. Build it first: .\build.ps1 -Configuration $Configuration -NoBump"
}

# Do not label a stale or differently targeted payload with the current version/RID.
function Assert-WindowsX64Executable {
    param([string]$Path)
    $reader = [System.IO.BinaryReader]::new([System.IO.File]::OpenRead($Path))
    try {
        $reader.BaseStream.Position = 0x3c
        $peOffset = $reader.ReadInt32()
        $reader.BaseStream.Position = $peOffset
        if ($reader.ReadUInt32() -ne 0x00004550 -or $reader.ReadUInt16() -ne 0x8664) {
            throw "Native payload must be a Windows x64 executable: $Path"
        }
    }
    finally {
        $reader.Dispose()
    }
}

if ($Flavor -ne 'engine') {
Assert-WindowsX64Executable $rustExe
$reported = & $rustExe --version
if ($LASTEXITCODE -ne 0 -or "$reported".Trim() -ne "coda $semVer") {
    throw "Native payload version '$reported' does not match coda $semVer. Rebuild before publishing."
}

# Regenerate version.props so the launcher project gets the right version stamp.
$asmVer = "$semVer.0"
@"
<Project>
  <!-- GENERATED by publish.ps1 from version.json. Do not edit. -->
  <PropertyGroup>
    <Version>$semVer</Version>
    <AssemblyVersion>$asmVer</AssemblyVersion>
    <FileVersion>$asmVer</FileVersion>
    <InformationalVersion>$semVer</InformationalVersion>
  </PropertyGroup>
</Project>
"@ | Set-Content (Join-Path $root 'version.props') -Encoding utf8
}

function Publish-RustSelfContained {
    $out = Join-Path $publishRoot 'self-contained'
    Reset-OutputDir $out
    Write-Host "==> self-contained (Rust) -> $out" -ForegroundColor Yellow
    Copy-Item $rustExe (Join-Path $out 'coda.exe') -Force
}

function Publish-RustFrameworkDependent {
    # The Rust binary has no .NET framework dependency. This flavor is kept for
    # compatibility with scripts that expect it; it produces the same binary.
    $out = Join-Path $publishRoot 'framework-dependent'
    Reset-OutputDir $out
    Write-Host "==> framework-dependent (Rust — same binary, no framework needed) -> $out" -ForegroundColor Yellow
    Copy-Item $rustExe (Join-Path $out 'coda.exe') -Force
}

function Publish-RustTool {
    $out = Join-Path $publishRoot 'tool'
    Reset-OutputDir $out
    Write-Host "==> global tool (Coda.Cli / Rust launcher) -> $out" -ForegroundColor Yellow
    $launcherProject = Join-Path $root 'src\Coda.Launcher\Coda.Launcher.csproj'
    & dotnet pack $launcherProject -c $Configuration -o $out `
        /p:Version=$semVer /p:AssemblyVersion=$asmVer /p:FileVersion=$asmVer `
        "/p:NativePayloadDir=$nativeDir\"
    if ($LASTEXITCODE -ne 0) { throw "dotnet pack failed (exit $LASTEXITCODE)." }
}

function Publish-RustEngine {
    # Opt-in flavor: the standalone, TUI-free `coda-engine` binary. Validated
    # the same way `coda.exe` is above (PE architecture + reported version),
    # with its own product-name prefix ("coda-engine", not "coda") — the two
    # binaries are separate artifacts, not the same one renamed.
    $rustEngineExe = Join-Path $nativeDir 'coda-engine.exe'
    if (-not (Test-Path $rustEngineExe)) {
        throw "Rust binary not found at $rustEngineExe. Build it first: .\rust\build.ps1 -Configuration $Configuration -NoBump (builds both coda and coda-engine)."
    }
    Assert-WindowsX64Executable $rustEngineExe
    $engineReported = & $rustEngineExe --version
    if ($LASTEXITCODE -ne 0 -or "$engineReported".Trim() -ne "coda-engine $semVer") {
        throw "Native payload version '$engineReported' does not match coda-engine $semVer. Rebuild before publishing."
    }

    $out = Join-Path $publishRoot 'engine'
    Reset-OutputDir $out
    Write-Host "==> engine (Rust, TUI-free core) -> $out" -ForegroundColor Yellow
    Copy-Item $rustEngineExe (Join-Path $out 'coda-engine.exe') -Force
}

switch ($Flavor) {
    'self-contained'      { Publish-RustSelfContained }
    'framework-dependent' { Publish-RustFrameworkDependent }
    'tool'                { Publish-RustTool }
    'engine'              { Publish-RustEngine }
    'all' {
        # 'engine' is intentionally not part of 'all': it is a separate,
        # opt-in artifact for external orchestrators, not part of the default
        # `coda` distribution or the global-tool package.
        Publish-RustSelfContained
        Publish-RustFrameworkDependent
        Publish-RustTool
    }
}

Write-Host "Published Coda $semVer." -ForegroundColor Green
