<#
.SYNOPSIS
  Publishes the Coda CLI (src/Coda.Tui) at the CURRENT version (version.json — no
  bump). Produces one or more distributable flavors under ./publish:

    self-contained       Single coda.exe, bundles the .NET runtime (no install
                         needed). Largest file. -> publish/self-contained/coda.exe
    framework-dependent  Single coda.exe, needs the .NET 10 runtime installed.
                         Much smaller.          -> publish/framework-dependent/coda.exe
    tool                 .NET global tool package (Coda.Cli, command `coda`).
                         Install/upgrade via `dotnet tool`. -> publish/tool/*.nupkg

  Versions are stamped from version.json via the same version.props the build
  uses, so published artifacts report the current version through `coda --version`.

.EXAMPLE
  ./publish.ps1                         # all three flavors, win-x64, Release
  ./publish.ps1 -Flavor self-contained  # just the standalone exe
  ./publish.ps1 -Flavor tool            # just the global-tool nupkg
  ./publish.ps1 -Runtime win-arm64      # target Windows on ARM
  ./publish.ps1 -Flavor self-contained -Runtime linux-x64   # Linux build
  ./publish.ps1 -Flavor self-contained -Runtime osx-arm64   # macOS (Apple Silicon)

.NOTES
  Cross-platform: Coda runs on Windows, Linux, and macOS. Pick the target with
  -Runtime (win-x64 / win-arm64 / linux-x64 / osx-x64 / osx-arm64). On Windows
  credentials are encrypted with DPAPI; on Linux/macOS they use an AES-GCM file
  store with 0600 permissions (FileTokenStore). Both default to ~/.coda/credentials.

.NOTES
  Install the global tool from the produced package:
    dotnet tool install  --global --add-source ./publish/tool Coda.Cli
  Upgrade it later:
    dotnet tool update   --global --add-source ./publish/tool Coda.Cli
#>
[CmdletBinding()]
param(
    [ValidateSet('all', 'self-contained', 'framework-dependent', 'tool')]
    [string]$Flavor = 'all',
    [string]$Configuration = 'Release',
    [string]$Runtime = 'win-x64'
)

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$project = Join-Path $root 'src/Coda.Tui/Coda.Tui.csproj'
$publishRoot = Join-Path $root 'publish'

# --- Resolve and stamp the current version (no bump) ---------------------------
$version = Get-Content (Join-Path $root 'version.json') -Raw | ConvertFrom-Json
$semVer = "{0}.{1}.{2}" -f [int]$version.major, [int]$version.minor, [int]$version.build
$asmVer = "$semVer.0"
Write-Host "Publishing Coda $semVer ($Configuration, $Runtime)" -ForegroundColor Cyan

@"
<Project>
  <!-- GENERATED by publish.ps1 from version.json. Do not edit. -->
  <PropertyGroup>
    <Version>$semVer</Version>
    <AssemblyVersion>$asmVer</AssemblyVersion>
    <FileVersion>$asmVer</FileVersion>
    <InformationalVersion>$semVer</InformationalVersion>
  </PropertyGroup>
</Project>
"@ | Set-Content (Join-Path $root 'version.props') -Encoding utf8

$versionArgs = @("/p:Version=$semVer", "/p:AssemblyVersion=$asmVer", "/p:FileVersion=$asmVer")

function Invoke-Checked {
    param([string[]]$Arguments)
    & dotnet @Arguments
    if ($LASTEXITCODE -ne 0) { throw "dotnet $($Arguments -join ' ') failed (exit $LASTEXITCODE)." }
}

# The exe ships as `coda.exe`. We rename the published single file rather than
# overriding AssemblyName, because that property propagates to every referenced
# project and makes them all build an assembly named "coda" (restore then fails
# with "Ambiguous project name 'coda'").
function Rename-PublishedExe {
    param([string]$OutputDir)
    # Windows publishes Coda.Tui.exe; Linux/macOS publish an extension-less Coda.Tui.
    $src = Join-Path $OutputDir 'Coda.Tui.exe'
    $dst = Join-Path $OutputDir 'coda.exe'
    if (-not (Test-Path $src)) {
        $src = Join-Path $OutputDir 'Coda.Tui'
        $dst = Join-Path $OutputDir 'coda'
    }
    if (Test-Path $src) {
        Move-Item -Path $src -Destination $dst -Force
    }
    # Drop loose debug symbols so the folder is just the shippable exe.
    Get-ChildItem -Path $OutputDir -Filter '*.pdb' -ErrorAction SilentlyContinue | Remove-Item -Force
}

# Wipe a flavor's output directory so each run is reproducible (no stale runtime
# DLLs from a different -Runtime, no accumulating .nupkg versions).
function Reset-OutputDir {
    param([string]$OutputDir)
    if (Test-Path $OutputDir) {
        Remove-Item -Recurse -Force $OutputDir
    }
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
}

# --- Self-contained single-file exe (no runtime install required) --------------
function Publish-SelfContained {
    $out = Join-Path $publishRoot 'self-contained'
    Reset-OutputDir $out
    Write-Host "==> self-contained -> $out" -ForegroundColor Yellow
    Invoke-Checked (@(
        'publish', $project, '-c', $Configuration, '-r', $Runtime,
        '--self-contained', 'true',
        '/p:PublishSingleFile=true',
        '/p:EnableCompressionInSingleFile=true',
        '/p:IncludeNativeLibrariesForSelfExtract=true',
        '-o', $out
    ) + $versionArgs)
    Rename-PublishedExe $out
}

# --- Framework-dependent single-file exe (needs .NET 10 runtime) ---------------
function Publish-FrameworkDependent {
    $out = Join-Path $publishRoot 'framework-dependent'
    Reset-OutputDir $out
    Write-Host "==> framework-dependent -> $out" -ForegroundColor Yellow
    Invoke-Checked (@(
        'publish', $project, '-c', $Configuration, '-r', $Runtime,
        '--self-contained', 'false',
        '/p:PublishSingleFile=true',
        '-o', $out
    ) + $versionArgs)
    Rename-PublishedExe $out
}

# --- .NET global tool package --------------------------------------------------
function Publish-Tool {
    $out = Join-Path $publishRoot 'tool'
    Reset-OutputDir $out
    Write-Host "==> global tool (Coda.Cli) -> $out" -ForegroundColor Yellow
    Invoke-Checked (@(
        'pack', $project, '-c', $Configuration, '-o', $out
    ) + $versionArgs)
}

switch ($Flavor) {
    'self-contained'      { Publish-SelfContained }
    'framework-dependent' { Publish-FrameworkDependent }
    'tool'                { Publish-Tool }
    'all' {
        Publish-SelfContained
        Publish-FrameworkDependent
        Publish-Tool
    }
}

Write-Host "Published Coda $semVer." -ForegroundColor Green
