namespace LlmClient;

/// <summary>Token consumption for one model turn or an accumulated session.</summary>
/// <param name="InputTokens">
/// Tokens that were not served from cache (the uncached remainder). This is the wire field
/// <c>input_tokens</c> from Anthropic's <c>message_start</c> usage event, which is one of
/// three <em>disjoint</em> input counters. The total context-window input is
/// <see cref="TotalInputTokens"/> = <see cref="InputTokens"/> + <see cref="CacheReadTokens"/> +
/// <see cref="CacheWriteTokens"/>.
/// </param>
/// <param name="OutputTokens">Tokens generated by the model.</param>
/// <param name="CacheReadTokens">Tokens served from an existing prompt-cache entry (wire: <c>cache_read_input_tokens</c>).</param>
/// <param name="CacheWrite5mTokens">Tokens written to a new cache entry with the 5-minute TTL (wire: <c>ephemeral_5m_input_tokens</c>).</param>
/// <param name="CacheWrite1hTokens">Tokens written to a new cache entry with the 1-hour TTL (wire: <c>ephemeral_1h_input_tokens</c>).</param>
public sealed record TokenUsage(
    int InputTokens,
    int OutputTokens,
    int CacheReadTokens = 0,
    int CacheWrite5mTokens = 0,
    int CacheWrite1hTokens = 0)
{
    /// <summary>A <see cref="TokenUsage"/> with all counters set to zero.</summary>
    public static TokenUsage Zero { get; } = new(0, 0);

    /// <summary>Returns a new <see cref="TokenUsage"/> with all five components summed.</summary>
    public TokenUsage Add(TokenUsage other) =>
        new(
            this.InputTokens + other.InputTokens,
            this.OutputTokens + other.OutputTokens,
            this.CacheReadTokens + other.CacheReadTokens,
            this.CacheWrite5mTokens + other.CacheWrite5mTokens,
            this.CacheWrite1hTokens + other.CacheWrite1hTokens);

    /// <summary>Total tokens written to cache across both TTL tiers (<see cref="CacheWrite5mTokens"/> + <see cref="CacheWrite1hTokens"/>).</summary>
    public int CacheWriteTokens => this.CacheWrite5mTokens + this.CacheWrite1hTokens;

    /// <summary>
    /// All tokens that occupied the context window and were billed in some form:
    /// uncached input + cache reads + cache writes.
    /// </summary>
    public int TotalInputTokens => this.InputTokens + this.CacheReadTokens + this.CacheWriteTokens;

    /// <summary>Total billed tokens: <see cref="TotalInputTokens"/> + <see cref="OutputTokens"/>.</summary>
    public int Total => this.TotalInputTokens + this.OutputTokens;

    /// <summary><see langword="true"/> when at least one cache counter is non-zero.</summary>
    public bool HasCacheActivity => this.CacheReadTokens > 0 || this.CacheWriteTokens > 0;
}
