using System.Collections.Immutable;
using Coda.Agent;
using Coda.Mcp;
using Coda.Sdk;
using Coda.Tui.Ui.Prompts;
using LlmClient;

namespace Coda.Tui.Ui.State;

/// <summary>
/// The complete, immutable UI state produced by <see cref="UiReducer"/>. Every field is a value or
/// an immutable, UI-facing snapshot — intentionally free of Terminal.Gui controls or mutable engine
/// instances so it can be diffed and rendered by any frontend.
/// </summary>
public sealed record UiSessionSnapshot(
    string? SessionId,
    string Provider,
    string Model,
    string? RequestedEffort,
    string EffectiveEffort,
    bool Connected,
    ContextStatus? Context,
    TokenUsage SessionUsage,
    decimal? EstimatedCost,
    string WorkingDirectory,
    GitStatus Git,
    PermissionStatus Permission,
    ServiceStatus Mcp,
    ServiceStatus Lsp,
    int RunningTasks,
    ActiveOperation? ActiveOperation,
    SessionRuntimeSnapshot? Runtime,
    McpRuntimeSnapshot? McpRuntime,
    ImmutableArray<TranscriptBlock> Transcript,
    UiNotification? Notification,
    string? StopReason,
    string Mode,
    UiPromptRequest? PendingPrompt = null,
    /// <summary>
    /// When <see langword="true"/>, assistant text and thinking output are buffered during a turn and
    /// rendered as a single block at turn completion instead of streaming token by token. Set once at
    /// session start from the registered hook set (<c>AnyHookMutatesDisplay</c>) and never changed
    /// by events, so the decision is static for the lifetime of the session.
    /// </summary>
    bool BufferAssistantText = false,
    /// <summary>
    /// The assistant text accumulated during a buffered turn, or <see langword="null"/> when no
    /// buffered turn is active. Non-null (including empty string) while a buffered turn is in flight;
    /// reset to <see langword="null"/> on turn completion or interruption.
    /// </summary>
    string? AssistantBuffer = null,
    /// <summary>
    /// The UTC timestamp at which the current buffered turn started. Used by
    /// <see cref="Coda.Tui.Ui.State.OperationalStatusProjector"/> to compute the live elapsed time
    /// for the animated placeholder. <see langword="null"/> when no buffered turn is active.
    /// </summary>
    DateTimeOffset? BufferingStartedAt = null,
    /// <summary>
    /// Output tokens generated by the model during the current buffered turn, accumulated from
    /// <see cref="Coda.Tui.Ui.Events.UsageEvent"/>s. Used by the animated placeholder to show
    /// progress. Reset to zero when the buffered turn ends.
    /// </summary>
    int BufferedOutputTokens = 0,
    /// <summary>
    /// <see langword="true"/> when a <see cref="Coda.Tui.Ui.Events.ResponseRewrittenEvent"/> was
    /// applied during the current buffered turn, indicating the buffer has been replaced with the
    /// hook's <c>displayContent</c> output. When <see langword="false"/> on interruption or error
    /// the buffer still contains raw model text that the redaction hook never inspected, and the
    /// UI must show a marker instead of the raw content.
    /// Reset to <see langword="false"/> at the start of each new turn.
    /// </summary>
    bool BufferRewrittenByHook = false)
{
    /// <summary>The initial, empty state before any event is applied.</summary>
    public static UiSessionSnapshot Empty { get; } = new(
        SessionId: null,
        Provider: string.Empty,
        Model: string.Empty,
        RequestedEffort: null,
        EffectiveEffort: "auto",
        Connected: false,
        Context: null,
        SessionUsage: TokenUsage.Zero,
        EstimatedCost: null,
        WorkingDirectory: Directory.GetCurrentDirectory(),
        Git: new GitStatus(null, false),
        Permission: new PermissionStatus(PermissionMode.Default, 0),
        Mcp: new ServiceStatus(0, 0),
        Lsp: new ServiceStatus(0, 0),
        RunningTasks: 0,
        ActiveOperation: null,
        Runtime: null,
        McpRuntime: null,
        Transcript: [],
        Notification: null,
        StopReason: null,
        Mode: "plain",
        PendingPrompt: null);
}
